### ISSUE TITLE
Data_2d_custom_myvideos.npz

### ISSUE THREAD

**Issue by grfleming** [DarrenJiang13/VideoPose3DwithDetectron2#1]
i am trying to run this, but there is no such file or directory on run:

Loading dataset...
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    dataset = CustomDataset('data/data_2d_' + args.dataset + '_' + args.keypoints + '.npz')
  File "~/pose/VideoPose3DwithDetectron2/common/custom_dataset.py", line 32, in __init__
    data = np.load(detections_path, allow_pickle=True)
  File "~/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_2d_custom_myvideos.npz'
Video Processing Finished. Output video is in the /output folder of the project directory.

where can i find this?

**Comment by CHDQ** [comment]
https://github.com/facebookresearch/VideoPose3D/blob/master/DATASETS.md

**Comment by ayush9198gupta** [comment]
Hi , Any link to get this npz file
